### ISSUE TITLE
Layer not found when trying mllm in Google Colab

### ISSUE THREAD

**Issue by gsamaras** [UbiquitousLearning/mllm#93]
I tried the Linux section of your README in Google Colab, where the installation succeeded. However, when trying to run the demo, the model returned no actual response, just rubbish, maybe empty response., and I got a bunch of messages that layers (of the model I suppose) were not found.

What I want to achieve is to have the mllm in a notebook, and then I send a sample query and I receive a sample response, nothing more exquisite. Is there such a notebook to run an example already available?

**Comment by lx200916** [comment]
1. I have learned that you wish to run mllm in Google Colab; however, currently mllm only offers C++ interfaces and Android interfaces based on JNI. Therefore, executing mllm in an ipynb file appears to be unfeasible.

2. I surmise that you might be running mllm using our command-line demo. In this scenario, the error `layers were not found` could potentially be due to a mismatch in model weights. Could you please provide detailed error information to facilitate troubleshooting?

**Comment by gsamaras** [comment]
Hi @lx200916, if not possible to run in Google Colab, then is there an online hosting solution to try mllm?

I executed the command-line demo, with the help of this video [run c++ in google colab](https://www.youtube.com/watch?v=37Edun_FCk8&ab_channel=BrianByrne), but if it does not make sense, I do not want to waste your time with troubleshooting. :)

**Comment by lx200916** [comment]
for now MLLM is more focused on mobile device inference frameworks, so we tend to assume that users are utilizing the CPU/NPU inference models on mobile devices. However, you can also use CMake to execute in a Linux x86 environment (perhaps the Colab environment is also available), but you may need to pay attention to issues such as the paths for loading model files and vocabularies.

**Comment by lx200916** [comment]
well, sometimes some hosting envs do not provide root permission but you can install some package(git or cmake included) to user-specific path via conda(or miniconda). BTW you can use pip to install cmake.

**Comment by chenghuaWang** [comment]
> @lx200916 I see, I just wanted to test it out in a standalone online environment first, do you know where I can try online with CMake? I tried a random linux online hosting service, but it wouldn't allow me to install git, thus I wasn't able to get the code.

@gsamaras I'm glad you're interested in the mllm project. I just tested it on Google Colab, and mllm can run on Colab. You can refer to this GitHub repository for an example notebook: [mllm-notebook-example](https://github.com/chenghuaWang/mllm-notebook-example/blob/main/mllm_notebook_example.ipynb).

> What I want to achieve is to have the mllm in a notebook, and then I send a sample query and I receive a sample response, nothing more exquisite. Is there such a notebook to run an example already available?

Currently, mllm does not support Python API. To achieve the functionality you mentioned, you will need to make some modifications based on the file at [demno_qwen.cpp](https://github.com/UbiquitousLearning/mllm/blob/main/examples/demo_qwen.cpp). U just need a `std::cin` to get your inputs, I believe it will be very easy to implement. Good luck.

**Comment by chenghuaWang** [comment]
@gsamaras 
> Maybe I could specify a target for CMake? I am very rusty unfortunately with C++, so if you could assist it would be great to close this issue.

Yes, you can specify a target using CMake CLI. Try `cmake --build .. --config Release --target demo_qwen` instead of `cmake .. -DCMAKE_BUILD_TYPE=Release` in `build.sh` script.

Compiling the complete mllm on Colab takes a long time, :smiling_face_with_tear: . As far as I understand, the various demos in the current mllm CMake will recompile many things, perhaps an optimization with a static library could be used?@lx200916

**Comment by lx200916** [comment]
> Compiling the complete mllm on Colab takes a long time, 🥲 . As far as I understand, the various demos in the current mllm CMake will recompile many things, perhaps an optimization with a static library could be used?@lx200916

We might provide static libraries after the API of the entire project stabilizes, but considering the rapid evolution of the project, this might not be very appropriate 😂 (not to mention the pain of prebuilt static libraries in the C++ ecosystem).
